### ISSUE TITLE
Effect of Reduction Rate

### ISSUE THREAD

**Issue by ezou626** [thuhcsi/NeuFA#10]
Did you notice any differences in model inference quality with changing the reduction rate hyperparameter of the model?
I'm wondering because training takes significantly longer with a small reduction rate.

**Comment by petronny** [comment]
The reduction rate used here is the same as the reduction rate in Tacotron, which merges some frames of spectrograms into one step.

We use this parameter when we start developing our model.

And any reduction rate greater than 1 will affect the inference quality, since the model will predict the number of frame instead of the actual time for the boundaries. More frames there are, more precise the boundaries will be.

**Comment by ezou626** [comment]
Thank you for letting me know! I am currently training with a reduction rate of 4 because I need the model sooner and I'm using it for more of a proof of concept, so less accuracy is okay for now.
